version: "3"

networks:
  userblog:
    driver: bridge

services:

  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: userblog_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - userblog

  # php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userblog_php
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev
      MONGODB_URL: mongodb://${MONGO_USER:-app_user}:${MONGO_PASSWORD:-app_password}@userblog_mongodb:27017
      MONGODB_DB: ${MONGO_DB:-app_db}
    volumes:
      - ./:/var/www/app
    networks:
      - userblog

  # mongodb
  mongodb:
    image: mongo:6.0
    container_name: userblog_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-app_user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-app_password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-app_db}
    volumes:
      - mongo_data:/data/db
    networks:
      - userblog

volumes:
  mongo_data:

